### ISSUE TITLE
Menulibre totally empty with mate

### ISSUE THREAD

**Issue by bluesabre** [bluesabre/menulibre#40]
Running Solus linux with mate 1.20 desktop, Menulibre version 2.1.5

If I launch menulibre, it shows no menu entries at all: https://i.imgur.com/RaMzBcr.png

However, my mate applications menu works fine and shows all the expected entries, it's just menulibre that's not showing anything

If I downgrade to menulibre 2.1.4 it works and I see all the menu entries, so it seems that the 2.1.5 update broke something

Launchpad Details: [#LP1748681](https://bugs.launchpad.net/bugs/1748681) bwat47 - 2018-02-11 01:35:42 +0000

**Comment by bluesabre** [comment]
I also experience anomalies using this with MATE. I do not believe it is fully MATE compatible. I do not experience what you state, but I have issues with folder placement not matching and order of menu items.

I know that is somewhat unrelated to your post here, but I thought to join up and maybe evaluate MenuLibre with MATE with a bit wider scope.

Launchpad Details: [#LPC](https://bugs.launchpad.net/menulibre/+bug/1748681/comments/1) Brian - 2018-02-23 06:17:01 +0000

**Comment by bluesabre** [comment]
@bwat47 I was unable to get MenuLibre running in Solus MATE.

@Brian Which distribution are you using?

Generally, MenuLibre should automatically determine the correct menu files if the desktop environment is exporting XDG_MENU_PREFIX as outlined by the desktop specification.

https://specifications.freedesktop.org/menu-spec/menu-spec-latest.html

This should be set by the desktop environment, and at least set by the package maintainer's configuration.

When I tested MATE compatibility, I used Ubuntu MATE.

Launchpad Details: [#LPC](https://bugs.launchpad.net/menulibre/+bug/1748681/comments/2) Sean Davis - 2018-02-24 00:54:15 +0000

**Comment by bluesabre** [comment]
@Sean, do you mean you saw the same problem as me or that you weren't able to open it?

Launchpad Details: [#LPC](https://bugs.launchpad.net/menulibre/+bug/1748681/comments/3) bwat47 - 2018-02-25 00:34:29 +0000

**Comment by bluesabre** [comment]
I noticed that if I launch version 2.1.4 from the terminal it tells me: WARNING:menulibre: getDefaultMenuPrefix() 'No menu prefix found, MenuLibre will not function properly.'

However, it appears to work fine anyway

With version 2.1.5, I do *not* get any error when launching it from the terminal, but as shown in my screenshot it shows no menu entries at all.

I tried setting export XDG_MENU_PREFIX=mate- in my /etc/environment file, however this resulted in menulibre just not launching at all (both 2.1.4 and 2.1.5)


Launchpad Details: [#LPC](https://bugs.launchpad.net/menulibre/+bug/1748681/comments/4) bwat47 - 2018-02-25 02:06:09 +0000

**Comment by bluesabre** [comment]
I managed to get MenuLibre running on Solus MATE. I am able to confirm the bug that you are seeing, but not able to determine what is causing it.

From what I can tell, the detection code is all working as expected, and the menu files between Ubuntu MATE and Solus MATE are identical.

Launchpad Details: [#LPC](https://bugs.launchpad.net/menulibre/+bug/1748681/comments/5) Sean Davis - 2018-02-27 11:15:43 +0000

**Comment by bluesabre** [comment]
I'm using Solus with Mate 1.20. The menu prefix recognition works fine, however the problem exists in how menulibre reads the information. I use a patch in order to trick menulibre and use gnome-applications.menu even in a MATE session. Another workaround is to copy /usr/share/xdg/menus/gnome-applications.menu into ~/.config/menus/mate-applications.menu in order to trick menulibre again.

I haven't learned python (yet) so I cannot fully understand the code and help more. But probably you need to add specific conditions for some mate categories/names similar to what you've done for gnome. I see for example that the function getRequiredCategories() of util.py handles directories like `mate-development` for which you can just remove the prefix and name it 'Development' but it doesn't handle directories like `mate-utility-accessibility` which has name `Universal Access`. Same thing for getDirectoryName(directory_str) and getDirectoryNameFromCategory(name) functions (I haven't understood exactly how you use them, but I believe I understood more or less what they do)

Launchpad Details: [#LPC](https://bugs.launchpad.net/menulibre/+bug/1748681/comments/6) Thanos Apostolou - 2018-03-29 08:29:14 +0000

**Comment by bluesabre** [comment]
This should now be resolved!

**Comment by dgl-dev** [comment]
Seeing this same problem on Debian 11 in Chromebook 
`lesatdgl@penguin:~$ sudo apt install menulibre
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  menulibre
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 153 kB of archives.
After this operation, 1,504 kB of additional disk space will be used.
Get:1 https://deb.debian.org/debian bullseye/main amd64 menulibre all 2.2.1-1 [153 kB]
Fetched 153 kB in 1s (230 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package menulibre.
(Reading database ... 72055 files and directories currently installed.)
Preparing to unpack .../menulibre_2.2.1-1_all.deb ...
Unpacking menulibre (2.2.1-1) ...
Setting up menulibre (2.2.1-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for desktop-file-utils (0.26-1) ...
lesatdgl@penguin:~$ menulibre
No menu prefix found, MenuLibre will not function properly.

(menulibre:22168): Gtk-WARNING **: 16:24:20.865: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton

(menulibre:22168): Gtk-WARNING **: 16:24:20.997: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton
WARNING:menulibre: getDefaultMenuPrefix() 'No menu prefix found, MenuLibre will not function properly.'
WARNING:menulibre: getDefaultMenuPrefix() 'No menu prefix found, MenuLibre will not function properly.'
WARNING:menulibre: getDefaultMenuPrefix() 'No menu prefix found, MenuLibre will not function properly.'`
