### ISSUE TITLE
Unable to move launchers to another category/directory

### ISSUE THREAD

**Issue by midvok** [bluesabre/menulibre#78]
**OS:** Manjaro Linux x86_64 
**Kernel:** 5.10.19-1-MANJARO 
**DE:** GNOME 3.38.3 
**Gnome Extensions:** Arc-Menu, Dash to Panel

Hello, this menu manager looks really good and I like to use it to modify the app icons!

What I can't figure out is how to rearrange menu items to suit my needs. I can "Add Directory" to insert a new category in the side bar. But I can't move any existing launchers to that new category.
I tried these steps...
* Drag & drop in the side bar doesn't work
* Clicking the "plus" button in launcher categories... it gives me a context menu with some default categories, but there aren't the categories I've just created by "Add Directory".

So, is it somehow possible to rearrange the launchers into the custom categories created by "Add Directory"?

**Comment by bluesabre** [comment]
Thanks for reaching out! You are correct, there is not currently support for drag & drop in the sidebar. Instead, you can use the arrow buttons to move launchers in and out of directories. For newly created or empty directories, this works automatically. For non-empty directories, you have to expand them first for launchers to be added as children. Please see the attached video for a demonstration.

https://user-images.githubusercontent.com/1894517/133751123-b3078432-b0e1-44aa-815b-5bc0b1d28a99.mp4

**Comment by JeckPeppinger** [comment]
Nope, @bluesabre, your video is not helpful as it shows some magic that is not happening with the real app. I could move a launcher into an empty directory, i mean - the tool just "sucked it in", how does the tool know i want the launcher in the directory, rather than just stepping over it (up or down, but not into the directory)?

And how can directories be moved into other directories?

How can a launcher or directory be moved out of a directory?
